/**
 * sendmail.app.groovy
 *
 *
 *
 **/


definition(
    name: "sendmail",
    namespace: "neiljackson1984",
    author: "Neil Jackson",
    description: "Send email using your outlook.com email account (gmail support coming soon)",
    iconUrl: "",
    iconX2Url: ""
)

mappings {
     path("/runTheTestCode") { action: [GET:"runTheTestCode"] }
}

def mainTestCode(){
	def message = ""
	message += "\n\n";

    message += "initially, state.outbox is : " + state.outbox + "\n";

    long currentUnixTime = now();
    Date currentDate = new Date(currentUnixTime);

    message += "finally, state.outbox is : " + state.outbox + "\n";
    message += "state.foo is : " + state.foo + "\n";

    message += "ahoy\n";
 
   return message;
}


preferences {
    page(name: "pageOne")
}

def pageOne(){
    def myDate = new Date();
    def myDateFormat = (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));
    myDateFormat.setTimeZone(location.timeZone);
    
    dynamicPage(
    	name: "pageOne", 
        title: "sendmail", 
        // "allow the app to be installed from this page?" (i.e. "show the OK/Install button?") : yes
        install: true, 
        
        // "allow the app to be uninstalled from this page?" (i.e. "show the "Remove" button?") 
        uninstall: true 
    ) {
    	section() {
            label( 
            	title: "label:", 
                description: "Assign a label for this instance of this app", 
                required: false, 
                defaultValue: "sendmail --" + myDateFormat.format(myDate)
            );
            input(
                name: "foo", 
                type: "text", 
                title: "this is the title", 
                description: "this is the description",
                // defaultValue: "this is the default value",
                required:false
            
            );
        }



    	section(/*"input"*/) {
            input(
                name: "dimmer", 
                title: "dimmer that this SmartApp will watch:" ,
                type: "capability.switchLevel", 
                description: (getAllChildDevices().isEmpty() ? "NEW CHILD DEVICE" : "CHILD DEVICE: \n" + getAllChildDevices().get(0).toString() ),            
                required:false,
                submitOnChange:true 
                
                // we want to reload the page whenever this preference changes,
                // because we need to give mainPage a chance to either show or
                // not show the deviceName input according to whether we will be
                // creating a child device (which depends on whether the user
                // has selected a device)
            )
            if(!settings.dimmer){ 
                //if there is no selected dimmer input (i.e. if we will be creating and a managing a (virtual) dimmer as a child device)
            	input(
                	name: "preferredLabelForChildDevice", // "labelForNewChildDevice", 
                    title: "Specify a label for the child device", 
                    type:"text",
                    defaultValue: "personal logger " + myDateFormat.format(myDate),
                    required: false
                )
            } 
            
            if(settings.dimmer)
            {
            	paragraph ( "To create a new virtual dimmer as a child device, and use it as the dimmer that this SmartApp will watch, set the above input to be empty.");
            }
            
        }

        section(/*"output"*/) {
            input(
            	title: "logging destination url:",
                name:"logDestinationUrl", 
                type:"text", 
                description: "Insert the URL that you generated by following the instructions at https://wp.josh.com/2014/06/04/using-google-spreadsheets-for-logging-sensor-data/",
                required:false
            )
        }
    }
}

//{  LIFECYCLE FUNCTIONS
    def installed() {
        log.debug "Installed with settings: ${settings}"
        initialize()
    }

    def uninstalled() {
        log.trace "uninstalling and deleting child devices (if any)"
        getAllChildDevices().each {
            log.trace "deleting child device " + it.toString();
        deleteChildDevice(it.deviceNetworkId)
        }
    }

    def updated() {
        log.debug "Updated with settings: ${settings}"
        unsubscribe()
        initialize()
    }
//}

def initialize() {

}

def prettyPrint(x){
    return groovy.json.JsonOutput.prettyPrint(groovy.json.JsonOutput.toJson(x));
}



//==========  WE DO ALL OUR INCLUDES AT THE BOTTOM IN ORDER TO PRESERVE THE MEANINGFULLNESS OF 
// LINE NUMBERS IN WARNING MESSAGES THROWN BY THE HUBITAT (AT LEAST IF THE WARNING MESSAGES ARE COMPLAINING
// ABOUT THINGS HAPPENING IN THE MAIN CODE, ABOVE THIS POINT).
#include "debugging.lib.groovy"